version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/docker-entrypoint-initdb.d
    networks:
      - event-reward-network

  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTH_SERVER_URL=http://auth-server:3001
      - EVENT_SERVER_URL=http://event-server:3002
      - JWT_SECRET=J6Yg7Nt2P9Z5bE4sXcWqKpLmVdRfTh3A
    depends_on:
      - auth-server
      - event-server
    networks:
      - event-reward-network

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/auth-db?authSource=admin
      - JWT_SECRET=J6Yg7Nt2P9Z5bE4sXcWqKpLmVdRfTh3A
    depends_on:
      - mongodb
    networks:
      - event-reward-network

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
    container_name: event-server
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/event-db?authSource=admin
      - AUTH_SERVER_URL=http://auth-server:3001
    depends_on:
      - mongodb
      - auth-server
    networks:
      - event-reward-network

networks:
  event-reward-network:
    driver: bridge

volumes:
  mongodb:
